
name: habit_tracker_app
description: A full-featured habit tracker with Firebase, offline cache, quotes, and charts.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/habits.png"