// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDccENrAnT1VEyzOv-ILK4LvHyIRFxGI8A',
    appId: '1:244573630367:web:76f7dcf47c13882ea6d7aa',
    messagingSenderId: '244573630367',
    projectId: 'habit-tracker-52c04',
    authDomain: 'habit-tracker-52c04.firebaseapp.com',
    storageBucket: 'habit-tracker-52c04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQYrq2klJeebAQfa-YMQbf4Yaz-VLItmI',
    appId: '1:244573630367:android:253c12c35fa97e2da6d7aa',
    messagingSenderId: '244573630367',
    projectId: 'habit-tracker-52c04',
    storageBucket: 'habit-tracker-52c04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUwysBh47ropL_cGX-1850Mbh9Pxs2Yjs',
    appId: '1:244573630367:ios:2101eff4634254b1a6d7aa',
    messagingSenderId: '244573630367',
    projectId: 'habit-tracker-52c04',
    storageBucket: 'habit-tracker-52c04.firebasestorage.app',
    iosBundleId: 'com.example.habitTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUwysBh47ropL_cGX-1850Mbh9Pxs2Yjs',
    appId: '1:244573630367:ios:2101eff4634254b1a6d7aa',
    messagingSenderId: '244573630367',
    projectId: 'habit-tracker-52c04',
    storageBucket: 'habit-tracker-52c04.firebasestorage.app',
    iosBundleId: 'com.example.habitTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDccENrAnT1VEyzOv-ILK4LvHyIRFxGI8A',
    appId: '1:244573630367:web:4d64d90f45232fb3a6d7aa',
    messagingSenderId: '244573630367',
    projectId: 'habit-tracker-52c04',
    authDomain: 'habit-tracker-52c04.firebaseapp.com',
    storageBucket: 'habit-tracker-52c04.firebasestorage.app',
  );
}
